# Generated by Django 5.1.3 on 2024-11-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('Active', 'Active'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
