# Generated by Django 5.1.3 on 2024-11-15 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loancustomer',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='loanprovider',
            name='contact_number',
        ),
    ]
