# Generated by Django 5.1.3 on 2024-11-16 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0001_initial'),
        ('users', '0002_remove_loancustomer_contact_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundapplication',
            name='user',
        ),
        migrations.AddField(
            model_name='fundapplication',
            name='LoanProvider',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.loanprovider'),
            preserve_default=False,
        ),
    ]
